### ISSUE TITLE
How can I create a server element without username or configuration?

### ISSUE THREAD

**Issue by zhanhb** [s4u/maven-settings-action#269] opened 2023-01-31 07:35 UTC
The server with id `gpg.passphrase` has only passphrase show as following. But when I try to do so, I got an error of `servers must contain id, and username or configuration`.

```xml
<server>
	<id>gpg.passphrase</id>
	<passphrase>${env.GPG_PASSPHRASE}</passphrase>
</server>
```

**Comment by slawekjaranowski** [comment] 2023-01-31 08:08
So look like we should required id only.

**Comment by slawekjaranowski** [comment] 2023-01-31 08:10
It looks like duplicate of #223

**Closed** 2023-01-31 08:12 UTC
